version: '3.8'

services:
  app:
    entrypoint:
    - sleep
    - infinity
    build: .
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

  postgres_db_data:
    image: postgres:13
    container_name: postgres_db_data
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: iie254007 
      POSTGRES_DB: data 
    volumes:
      - postgres_db_data:/var/lib/postgresql/data 
    ports:
      - 5433:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      start_period: 30s

volumes:
  postgres_db_data:
    driver: local