version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Iie254007.
      POSTGRES_DB: KingdomGame
    volumes:
      - ./db/data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: DockerfileBack
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/KingdomGame
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Iie254007.
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - backend
      - frontend
