# Utilisez l'image de base adoptopenjdk avec Java 19
FROM openjdk:19
# Définir le répertoire de travail dans l'image
WORKDIR /app

# Copier le fichier JAR de l'application dans le conteneur
COPY target/test-0.0.1-SNAPSHOT.jar app.jar

# Exposer le port utilisé par l'application
EXPOSE 8080

# Commande d'exécution de l'application Spring Boot
CMD ["java", "-jar", "app.jar"]
